name: ai_chat_app
description: "A new Flutter project."
publish_to: 'none' # ลบบรรทัดนี้หากคุณต้องการเผยแพร่ไปที่ pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.8  # ให้เหลือแค่บรรทัดนี้สำหรับ cupertino_icons
  mcp_llm: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
